
import React, { Suspense } from "react";
import "./globals.css";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Route",
  description: "This is Generated by create next app",
  openGraph: {
    title: "Next Route",
    description: "This dasboard is Generated by create next app",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSitV0j94LJrRn2ASeVUJIsY8Cg9csBYhyl-w&s",
    siteName: "Next Route",
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        {" "}
        <Suspense fallback={<div className="text-cyan-400">Loading...</div>}>
          {children}
        </Suspense>
        {/* <ErrorBoundary fallback={<Error />}></ErrorBoundary> */}
      </body>
    </html>
  );
}
